### ISSUE TITLE
Add CSS to allow button styles to be applied to links

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-button#2]
There are use cases in our apps where UX wants the look of a button but needs the behavior of a link. A common example is a modal trigger which is used to AJAX content into a modal. 

The trigger is an anchor element which links to a page and AJAXs content from that page into a modal if JavaScript is enabled. If JavaScript is not available, the modal trigger still allows the user to view the content by functioning as a proper link. Commonly in our apps, these modal triggers are designed to appear as buttons.

One thing to consider when adding this functionality is that JavaScript will be required to emulate the disabled state which button elements can have.

Another thing we should add is documentation around links used as buttons:

From Bootstrap's documentation:
"When using button classes on <a> elements that are used to trigger in-page functionality (like collapsing content), rather than linking to new pages or sections within the current page, these links should be given a role="button" to appropriately convey their purpose to assistive technologies such as screen readers."

__Desired Results:__
* Links can be styled with `terra-Button` classes
* Update documentation on accessibility considerations around anchors and buttons
* Links styled as buttons handle disabled state appropriately

**Comment by gneatgeek** [comment]
We've discussed this enhancement further and decided that we will re-address should someone need the functionality.
