### ISSUE TITLE
terra-button-color documentation not found

### ISSUE THREAD

**Issue by mschile** [cerner/terra-button#23]
### Description of Issue
The terra-button-color documentation is not found when trying to view it from [1]. terra-button-context.md should be named terra-button-color.md

[1] https://github.com/cerner/terra-button/blob/master/docs/README.md

**Comment by mjhenkes** [comment]
@mschile Thanks for taking a look at Terra and taking the initiative to help make it better.

We've migrated terra button from here to our new mono repo. https://github.com/cerner/terra-ui/tree/master/packages/terra-button In the process of this transition, I think we've corrected this issue.

We're not accepting pull requests to this branch as it's being depreciated and will be deleted soon.

Thanks again!
