### ISSUE TITLE
Block style buttons

### ISSUE THREAD

**Issue by gneatgeek** [cerner/terra-button#5]
I'd like to have buttons that expand to fill the width of their parent element to provide a large click target.

__Desired Results:__
- Displays at full width of parent container

**Comment by TatianaAlexenko** [comment]
I'll give it a shot.

**Comment by gneatgeek** [comment]
Hi @TatianaAlexenko, thanks for your interest in working on this issue.  If you have any questions or need any help with this, please reach out and we'll be happy to help.

**Comment by gneatgeek** [comment]
@TatianaAlexenko, I wanted to let you know that we've discussed this issue further and decided that it's probably best to hold off on the responsive styles for now since the grid system is able to handle that issue. 

Let me know if you have any concerns with that.

**Comment by bjankord** [comment]
Resolved in #8. Thanks @bunnyLord for this enhancement!
